### ISSUE TITLE
New installation error 

### ISSUE THREAD

**Issue by johnfelipe** [Code4SA/pmg-cms-2#13]
Running setup.py (path:/home/notroot/pmg-cms-2/env/build/psycopg2/setup.py) egg_info for package psycopg2
		running egg_info
		creating pip-egg-info/psycopg2.egg-info
		writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
		writing pip-egg-info/psycopg2.egg-info/PKG-INFO
		writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
		writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
		warning: manifest_maker: standard file '-c' not found
		
		Error: pg_config executable not found.
		
		Please add the directory containing pg_config to the PATH
		or specify the full executable path with the option:
		
			python setup.py build_ext --pg-config /path/to/pg_config build ...
		
		or with the pg_config option in 'setup.cfg'.
		Complete output from command python setup.py egg_info:
		running egg_info

	creating pip-egg-info/psycopg2.egg-info

	writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt

	writing pip-egg-info/psycopg2.egg-info/PKG-INFO

	writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt

	writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

	warning: manifest_maker: standard file '-c' not found

	Error: pg_config executable not found.

	Please add the directory containing pg_config to the PATH

	or specify the full executable path with the option:

		python setup.py build_ext --pg-config /path/to/pg_config build ...

	or with the pg_config option in 'setup.cfg'.

	----------------------------------------
	Cleaning up...
	  Removing temporary dir /home/notroot/pmg-cms-2/env/build...
	Command python setup.py egg_info failed with error code 1 in /home/notroot/pmg-cms-2/env/build/psycopg2
	Exception information:
	Traceback (most recent call last):
	  File "/home/notroot/pmg-cms-2/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
		status = self.run(options, args)
	  File "/home/notroot/pmg-cms-2/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
		requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
	  File "/home/notroot/pmg-cms-2/env/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
		req_to_install.run_egg_info()
	  File "/home/notroot/pmg-cms-2/env/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
		command_desc='python setup.py egg_info')
	  File "/home/notroot/pmg-cms-2/env/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
		% (command_desc, proc.returncode, cwd))
	InstallationError: Command python setup.py egg_info failed with error code 1 in /home/notroot/pmg-cms-2/env/build/psycopg2

**Comment by johnfelipe** [comment]
Hi, please tell me something about it

**Comment by adieyal** [comment]
on ubuntu, you can install it with this command

sudo aptitude install postgresql postgresql-contrib-8.4
