### ISSUE TITLE
Sort search results by date

### ISSUE THREAD

**Issue by adieyal** [Code4SA/pmg-cms-2#54]
I am currently search for results in Hansards. I know that I am looking for a result in October 2009. I can filter by year but not by month. This means that I need to scan through the results. It would be much quicker if the results were sorted by date so that I can skip to the correct page in the results.

**Comment by longhotsummer** [comment]
It's currently sorted by relevance. We could add a sort-by-date feature, or allow the user to drill down into months after drilling down into a year.

**Comment by adieyal** [comment]
Relevance isn't that good if the results aren't relevant.

On Wed, Aug 5, 2015 at 9:31 AM, Greg Kempe <notifications@github.com> wrote:

> It's currently sorted by relevance. We could add a sort-by-date feature,
> or allow the user to drill down into months after drilling down into a year.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4SA/pmg-cms-2/issues/54#issuecomment-127899620>.
>



-- 
Adi Eyal
Director
Code for South Africa
Promoting informed decision-making

phone: +27 78 014 2469
skype: adieyalcas
linkedin: http://za.linkedin.com/pub/dir/Adi/Eyal
web: http://www.code4sa.org
twitter: @soapsudtycoon

Follow us on twitter at @code4sa
For more information on how to participate in the open data community in
South Africa, go to: http://www.code4sa.org/#community
Sign up for Naked Data, our weekly round-up of what's happening locally and
internationally in data journalism and data visualisation. Register here:
http://www.code4sa.org/newsletter

**Comment by longhotsummer** [comment]
Heh, very true. Perhaps relevance is the wrong word, it's sorting by Elasticsearch score. I think both per-month drilldown and ordering by date would be useful features.
