### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by johnfelipe** [Code4SA/pmg-cms-2#8]
Hi, please tell me how fix this:

	notroot@dhcppc5:~$ cd pmg-cms-2/
	notroot@dhcppc5:~/pmg-cms-2$ virtualenv --no-site-packages env
	New python executable in env/bin/python
	Installing setuptools, pip...done.
	notroot@dhcppc5:~/pmg-cms-2$ source env/bin/activate
	(env)notroot@dhcppc5:~/pmg-cms-2$ pip install -r requirements.txt
	Downloading/unpacking git+http://github.com/Code4SA/flask-security.git@2.0.2 (from -r requirements.txt (line 9))
	  Cloning http://github.com/Code4SA/flask-security.git (to 2.0.2) to /tmp/pip-kbcKV0-build
	  Running setup.py (path:/tmp/pip-kbcKV0-build/setup.py) egg_info for package from git+http://github.com/Code4SA/flask-security.git@2.0.2

		warning: no previously-included files matching '*' found under directory 'tests/__pycache__'
	Downloading/unpacking Fabric==1.10.0 (from -r requirements.txt (line 1))
	  Downloading Fabric-1.10.0.tar.gz (208kB): 208kB downloaded
	  Running setup.py (path:/home/notroot/pmg-cms-2/env/build/Fabric/setup.py) egg_info for package Fabric

		warning: no previously-included files matching '*' found under directory 'sites/docs/_build'
		warning: no previously-included files matching '*' found under directory 'sites/www/_build'
		warning: no previously-included files matching '*.pyc' found under directory 'tests'
		warning: no previously-included files matching '*.pyo' found under directory 'tests'
	Downloading/unpacking Flask==0.10.1 (from -r requirements.txt (line 2))
	  Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded
	  Running setup.py (path:/home/notroot/pmg-cms-2/env/build/Flask/setup.py) egg_info for package Flask

		warning: no files found matching '*' under directory 'tests'
		warning: no previously-included files matching '*.pyc' found under directory 'docs'
		warning: no previously-included files matching '*.pyo' found under directory 'docs'
		warning: no previously-included files matching '*.pyc' found under directory 'tests'
		warning: no previously-included files matching '*.pyo' found under directory 'tests'
		warning: no previously-included files matching '*.pyc' found under directory 'examples'
		warning: no previously-included files matching '*.pyo' found under directory 'examples'
		no previously-included directories found matching 'docs/_build'
		no previously-included directories found matching 'docs/_themes/.git'
	Downloading/unpacking Flask-Admin==1.0.9.dev0 (from -r requirements.txt (line 3))
	  Could not find a version that satisfies the requirement Flask-Admin==1.0.9.dev0 (from -r requirements.txt (line 3)) (from versions: 0.1.3.linux-x86_64, 0.1.1, 0.1.2, 0.1.2, 0.1.3, 0.1.3, 0.1.4, 0.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
	  Some externally hosted files were ignored (use --allow-external to allow).
	Cleaning up...
	No distributions matching the version for Flask-Admin==1.0.9.dev0 (from -r requirements.txt (line 3))
	Storing debug log for failure in /home/notroot/.pip/pip.log

**Comment by johnfelipe** [comment]
Please help me

**Comment by petrus-jvrensburg** [comment]
Hi Felipe, thanks for logging this.

Flask-Admin's 1.0.9 version was recently released, so that's why the 1.0.9.dev0 version could no longer be found. I just updated the requirements file to fix that.
