### ISSUE TITLE
Translate for spanish is possible

### ISSUE THREAD

**Issue by johnfelipe** [Code4SA/pmg-cms-2#9]
Tnks

**Comment by johnfelipe** [comment]
Is possible translate for other lang include spanish?

**Comment by johnfelipe** [comment]
Hi, me again, pls tell me...

**Comment by longhotsummer** [comment]
It's technically possible to do a translation, however it would take some time and effort and we do not have budget for a Spanish translation, given that Spanish is not an official language of South Africa. You're welcome to contribute a translation if you desire.

**Comment by johnfelipe** [comment]
Transifex is possible. look
https://www.transifex.com/projects/p/sayit/translate/#es/project
Something like that

**Comment by johnfelipe** [comment]
I will translate, but code not work for me

**Comment by johnfelipe** [comment]
If you give me vocabulary i translate to spanish

**Comment by johnfelipe** [comment]
Good idea multilanguage, i can contribute in spanish translation

**Comment by johnfelipe** [comment]
I can translate strings, its possible?
